<div id="searchGbox">
<div id="cse-search-form" style="width: 100%;">Loading</div>
{literal}
<script src="http://www.google.com/jsapi" type="text/javascript"></script>
<script type="text/javascript"> 
  google.load("search", "1", {language : "ja"});
  google.setOnLoadCallback(function() {
    var customSearchControl = new google.search.CustomSearchControl("002073739407078901360:qt4vvd5tu4c");
    customSearchControl.setResultSetSize(google.search.Search.FILTERED_CSE_RESULTSET);
    var options = new google.search.DrawOptions();
    options.enableSearchboxOnly("http://www.hotei.or.jp/search/");    
    customSearchControl.draw("cse-search-form", options);
  }, true);
</script>
{/literal}
</div>
