<div id="header_container">
<div id="header">
<div id="logo"><a href="http://www.hotei.or.jp/"><img src="/common/img/logo01.gif" alt="矯正歯科　大阪【ほてい矯正歯科】" width="271" height="23" /></a></div>
<ul id="hnavi">
<li><a href="/clinic_sakai/index.html"><img src="/common/img/gn_clinicsakai.gif" alt="堺クリニック" width="107" height="56" class="on" /></a></li>
<li><a href="/clinic_senri/index.html"><img src="/common/img/gn_clinicsenri.gif" alt="千里クリニック" width="119" height="56" class="on" /></a></li>
<li><a href="/inquiry/index.html"><img src="/common/img/gn_inquiry.gif" alt="お問い合わせ" width="108" height="56" class="on" /></a></li>
</ul>
<ul id="gnavi">
<li><a href="http://www.hotei.or.jp/"><img src="/common/img/gn_top.gif" alt="トップページ" width="132" height="29" class="on" /></a></li>
<li><a href="/about/index.html"><img src="/common/img/gn_about.gif" alt="ほてい矯正歯科クリニックについて" width="244" height="29" class="on" /></a></li>
<li><a href="/staff/index.html"><img src="/common/img/gn_staff.gif" alt="スタッフ" width="112" height="29" class="on" /></a></li>
<li><a href="/chiryo/index.html"><img src="/common/img/gn_chiryo.gif" alt="治療案内" width="98" height="29" class="on" /></a></li>
<li><a href="/case/"><img src="/common/img/gn_case_on.gif" alt="症例紹介" width="116" height="29" /></a></li>
<li><a href="/happysmile/index.php"><img src="/common/img/gn_happysmile.gif" alt="みんなの笑顔" width="120" height="29" class="on" /></a></li>
<li><a href="/sitemap/index.html"><img src="/common/img/gn_sitemap.gif" alt="サイトマップ" width="128" height="29" class="on" /></a></li>
</ul>
<p class="breadcrumb"><a href="http://www.hotei.or.jp/">トップページ</a> ＞ 症例紹介</p>
</div>
</div>
