<meta name="description" content="患者さんの様々な症例を紹介します。 矯正歯科大阪(堺・千里)の歯列矯正なら「ほてい矯正歯科」" />
<meta name="keywords" content="症例,矯正,歯科,大阪,堺,千里,歯列,治療" />
<meta http-equiv="Content-Style-Type" content="text/css" />
<meta http-equiv="Content-Script-Type" content="text/javascript" />
<link rel="shortcut icon" href="/common/img/favicon.ico">
<link rel="stylesheet" href="/common/css/common.css" type="text/css" media="screen, all" />
<link rel="stylesheet" href="/case/css/case.css" type="text/css" media="screen, all" />
<script type="text/javascript" src="/case/js/import_case.js"></script>
