<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="ja" xml:lang="ja">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>症例紹介システム　管理画面</title>
<meta name="description" content="" />
<meta name="keywords" content="" />
<meta http-equiv="Content-Style-type" content="text/css" />
<meta http-equiv="Content-Script-type" content="text/javascript" />
<link rel="stylesheet" href="/case/admin/css/import.css" type="text/css" media="screen,all" />
<script type="text/javascript" src="/case/admin/js/import.js" charset="utf-8"></script>
